apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nupic-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nupic-models
  volumeName: nupic-models