apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "f5xc-triton.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ include "f5xc-triton.fullname" . }}
  volumeName: {{ include "f5xc-triton.fullname" . }}