apiVersion: v1
kind: Service
metadata:
  name: {{ include "f5xc-triton.fullname" . }}
  labels:
    {{- include "f5xc-triton.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}

  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    {{- include "f5xc-triton.selectorLabels" . | nindent 4 }}
